spring.graphql.graphiql.enabled: true
spring.graphql.websocket.path: /graphql

spring.kafka:
    bootstrap-servers: "[::1]:9092"
    consumer:
      group-id: kafka-spring-graphql
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: com.github.dannil.demo.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
